import { Router } from "express";
import userRouter from "../user/signUp/index.js";
import loginRouter from "../authentication/login/index.js";
import forgetPasswordRouter from "../user/forgetPassword/index.js";
import productPostRouter from "../product/post/index.js";
import imageGetRouter from "../product/get/index.js";
import updatepasswordRouter from "../user/passwordUpdate/index.js";
import searchRouter from "../search/get/index.js";
import orderRouter from "../user/order/index.js";
import stripePostRouter from "../stripe/post/index.js";
const allRouters = Router();
allRouters.use(userRouter);
allRouters.use(loginRouter);
allRouters.use(forgetPasswordRouter);
allRouters.use(productPostRouter);
allRouters.use(imageGetRouter);
allRouters.use(updatepasswordRouter);
allRouters.use(searchRouter);
allRouters.use(orderRouter);
allRouters.use(stripePostRouter);
export default allRouters;
